language: objective-c
osx_image: xcode7
xcode_sdk:
  - iphonesimulator9.0
before_install:
  - brew update
  - brew reinstall xctool
  - gem install cocoapods -v 0.37.2
  - xcrun simctl list
install: echo "<3"
env:
  - MODE=tests
  - MODE=examples
  - MODE=life-without-cocoapods
script: ./build.sh $MODE

# whitelist
branches:
  only:
    - master
