language: objective-c
before_install:
  - brew update
  - brew reinstall xctool
  - gem update cocoapods
  - xcrun simctl list
env:
  - MODE=tests
  - MODE=examples
script: ./build.sh $MODE

# whitelist
branches:
  only:
    - master
